### PR TITLE
W-035650 Edit Donor Modal

### LINKED ISSUE #207: SGE: Internal Server Error if editing contact and contact page layout has Pardot components
* **What is the current behavior?**

Using Single Gift Entry, select 'Edit Contact' button and make any edit to Contact, Save

The data saves to Contact, but SGE page renders error:

`Uncaught Error in $A.getCallback() [Value is not a string, ObjectId, or FieldId.]`

* **What is the expected behavior?**

After saving Contact error, user should be able to continue with Single Gift Entry form.

* **Workaround/Cause**

The issue is with Pardot Visualforce components on the Contact page layout. When those components are removed, the page saves normally. We need to determine where the conflict is in these components.

In the meantime, users should edit Contacts directly on the Contact record and not through Single Gift Entry.

### PR DESCRIPTION
**Pull request by bdvorachek**
# Critical Changes

# Changes
- We've swapped out the components used to drive the Donor Edit functionality on the Single Gift Entry form to fix some unwanted behaviors that occurred when certain Visualforce pages were present on the user's assigned page layout.
# Issues Closed
Closes #207 
# New Metadata
- Aura Components
  - giftEntryEditDonorBody
  - giftEntryEditDonorFooter
- Labels
  - Saving - Alternative text for a spinner inside the new modal
  - Edit_Donor - Title for Modal when editing either an Account or Contact
# Deleted Metadata

# Testing Notes

### CODE REVIEW

File: src/aura/giftEntryForm/giftEntryFormController.js [hunk 1]
```diff
@@ -144,15 +133,19 @@
...
+        if(!donorId){
+            return;
+        }
 
 
         $A.createComponents([
             ['c:giftEntryEditDonorBody', {
                 'aura:id': 'donorEditModalBody',
                 'recordId': donorId,
-                'objectApiName': 'Contact',
```
Comment (bdvorachek) [inline src/aura/giftEntryForm/giftEntryFormController.js]: 👍

**Comment by annejackson** [comment]
Testing complete. Merging PR.
